### ISSUE TITLE
Something went wrong with the action

### ISSUE THREAD

**Issue by atomlab** [docpad/docpad-skeleton-syte#14]
Hello. I have trouble with install "syte".

./syte.docpad$ docpad run

```
error: Failed to load the configuration path: /home/nodejs/sites/syte.docpad/docpad.coffee
error: Something went wrong with the action
error: An error occured: 
TypeError: string is not a function
    at Object.<anonymous> (/home/nodejs/sites/syte.docpad/docpad.coffee:87:64)
    at Object.<anonymous> (/home/nodejs/sites/syte.docpad/docpad.coffee:252:4)
    at Module._compile (module.js:456:26)
    at Object.loadFile (/home/nodejs/sites/syte.docpad/node_modules/docpad/node_modules/cson/node_modules/coffee-script/lib/coffee-script/coffee-script.js:182:19)
    at Module.load (/home/nodejs/sites/syte.docpad/node_modules/docpad/node_modules/cson/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.app.requireFresh (/home/nodejs/sites/syte.docpad/node_modules/docpad/node_modules/cson/node_modules/requirefresh/out/lib/requirefresh.js:30:14)
    at /home/nodejs/sites/syte.docpad/node_modules/docpad/node_modules/cson/node_modules/requirefresh/out/lib/requirefresh.js:16:22
    at b (domain.js:183:18)
    at Domain.run (domain.js:123:23)
    at app.requireFreshSafe (/home/nodejs/sites/syte.docpad/node_modules/docpad/node_modules/cson/node_modules/requirefresh/out/lib/requirefresh.js:13:7)
    at Object.CSON.parseFile (/home/nodejs/sites/syte.docpad/node_modules/docpad/node_modules/cson/out/lib/cson.js:28:9)
    at /home/nodejs/sites/syte.docpad/node_modules/docpad/out/lib/docpad.js:1583:23
    at Object.cb [as oncomplete] (fs.js:168:19)
info: Shutting down... cya next time!
```

How fix that? Thanks!

**Comment by dcardosods** [comment]
Same error here.

**Comment by karimtabet** [comment]
Same here, anyone find any solutions yet?

**Comment by chrisfranklin** [comment]
Deleting this bit from line 164 of docpad.coffee solved it for me:

```
    # Codepen
    Codepen:
      name: 'Codepen'
      url: "//codepen.io/#{envConfig.CODEPEN_USERNAME}"
        feeds:
          user: 'codepenUser'
```

**Comment by ghost** [comment]
same error here

**Comment by chrisfranklin** [comment]
Try the fix posted above.
