### ISSUE TITLE
Errors on docpad run

### ISSUE THREAD

**Issue by yumyo** [docpad/docpad-skeleton-syte#2]
```
error: Something went wrong with the action
error: An error occured: 
Error: Cannot find module 'feedr'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/Users/labs/Sites/syte.docpad/docpad.coffee:6:16)
    at Object.<anonymous> (/Users/labs/Sites/syte.docpad/docpad.coffee:262:4)
    at Module._compile (module.js:449:26)
    at Object.require.extensions..coffee (/usr/local/lib/node_modules/docpad/node_modules/cson/node_modules/coffee-script/lib/coffee-script/coffee-script.js:30:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

**Comment by vinhnglx** [comment]
Hi @yumyo. In file docpad.coffee. Please comment line feedr = new (require('feedr').Feedr), after run http://localhost:9778.

**Comment by balupton** [comment]
Also try `npm install feedr`

**Comment by balupton** [comment]
But please note, this skeleton is still expiremental and is currently used to define the requirements for importer plugins for docpad.

**Comment by vinhnglx** [comment]
Oooppp....thanks, @balupton  .....:)...I've only test with twitter and github :)
