### ISSUE TITLE
Blocking on Docpad run

### ISSUE THREAD

**Issue by weareburo** [docpad/docpad-skeleton-syte#6]
Console stop on task info: LiveReload listening to new socket on channel /docpad-livereload with log level 1
My .env is :+1: 

TUMBLR_BLOG=folawilliamsadidas.tumblr.com
TUMBLR_API_KEY=cMDLzJipAI4gD9AEFMAgtAzWRN0yKRa7MUweDZtQg70Z3IUfDr

Any clue ?

**Comment by balupton** [comment]
Run it with the `-d` flag, and post up the generate `docpad-debug.log` file somewhere.

**Comment by weareburo** [comment]
Thanks ,, i have that 
info: Importing Tumblr posts...
    → [2013-07-28 19:55:45.894] [/Users/jaminrubio/syte.docpad/node_modules/docpad-plugin-tumblr/out/tumblr.plugin.js:109] [TumblrPlugin.module.exports.TumblrPlugin.populateCollections]
error: An error occured: 
TypeError: Cannot read property 'length' of undefined
    at module.exports.TumblrPlugin.fetchTumblrData (/Users/jaminrubio/syte.docpad/node_modules/docpad-plugin-tumblr/out/tumblr.plugin.js:75:34)
    at Feedr.readFeed.writeFeed (/Users/jaminrubio/syte.docpad/node_modules/docpad-plugin-tumblr/node_modules/feedr/out/lib/feedr.js:186:18)
    at safefs.writeFile (/Users/jaminrubio/syte.docpad/node_modules/docpad-plugin-tumblr/node_modules/feedr/node_modules/safefs/out/lib/safefs.js:98:18)
    at Object.oncomplete (fs.js:297:15)
    → [2013-07-28 19:55:46.205] [/usr/local/lib/node_modules/docpad/out/lib/docpad.js:1834] [DocPad.error]

**Comment by balupton** [comment]
Looking into it now.

**Comment by balupton** [comment]
Can you pull in the latest skeleton changes, then run `docpad update`, and try `docpad run -d` again
